.PHONY: clean All

All:
	@echo "----------Building project:[ Notebook - Debug ]----------"
	@cd "Notebook" && "$(MAKE)" -f  "Notebook.mk"
clean:
	@echo "----------Cleaning project:[ Notebook - Debug ]----------"
	@cd "Notebook" && "$(MAKE)" -f  "Notebook.mk" clean
